# Generated by Django 5.0.3 on 2024-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='detection_results_images/'),
        ),
    ]
